language: go

go:
  - master

env:
  - GO111MODULE=on

before_install:
  go mod tidy && go test -v ./

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false